### PR TITLE
 InsertTimestamps: Fix broken chat patch

### PR DESCRIPTION
**Pull request by Huderon**
Boy, did I ever pull a boner. Sorry 😿

fix for #5

### CODE REVIEW

**Comment by stargatefreak** [comment]
Am I missing something? The button is still not showing up. It is enabled now but it's still not working.
msg bar
plugins

**Comment by Huderon** [comment]
Should be fine. It's kind of wonky, so if you enabled the plugin while that channel was open, you'll need to reload or switch channel once

**Comment by IskrenTs** [comment]
i did the change myself too but still no button  and no error message

**Comment by Huderon** [comment]
Is double oops, give it a go now

**Comment by stargatefreak** [comment]
Yep, it now works. Good job.

**Comment by Atomzwieback** [comment]
Works, please merge @Vendicated

**Pull request merged**
